name: Deploy to EC2

on:
  push:
    branches:
      - main  # The branch to trigger deployment (you can change this)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@13.203.161.48 "mkdir -p /home/ec2-user/app"
          scp -o StrictHostKeyChecking=no -r * ec2-user@13.203.161.48:/home/ec2-user/app

      - name: SSH into EC2 and restart the application
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@13.203.161.48 << 'EOF'
            cd /home/ec2-user/app
            # Assuming you're using a Node.js app
            npm install
            pm2 restart app.js  # Adjust according to your setup
          EOF
